load("@bazel_skylib//rules:run_binary.bzl", "run_binary")

objc_library(
    name = "glib-darwin",
    srcs = [
        "glib/gosxutils.m",
        "os/darwin/config.h",
        "os/darwin/glib/glibconfig.h",
    ] + glob(["glib/*.h"]),
    copts = [
        "-DGLIB_COMPILATION",
        "-D_GNU_SOURCE",
        "-DG_DISABLE_CAST_CHECKS",
        '-DGLIB_CHARSETALIAS_DIR=""',
        "-I $(execpath os/darwin)",
        "-I $(execpath os/darwin/glib)",
        "-I $(execpath glib)",
        "-I $(execpath .)",
    ],
    data = [
        # These paths are here so we can use them in copts with $(execpath ...)
        "os/darwin",
        "os/darwin/glib",
        "glib",
        ".",
    ],
    includes = [
        ".",
    ],
)

py_binary(
    name = "gen-visibility-macros",
    srcs = ["tools/gen-visibility-macros.py"],
)

run_binary(
    name = "gen_visibility_macros",
    outs = ["gmodule/gmodule-visibility.h"],
    args = [
        "2.77.2",
        "visibility-macros",
        "GMODULE",
        "$(location gmodule/gmodule-visibility.h)",
    ],
    tool = ":gen-visibility-macros",
)

cc_library(
    name = "gnulib",
    srcs = [
        "glib/gnulib/asnprintf.c",
        "glib/gnulib/isnan.c",
        "glib/gnulib/printf.c",
        "glib/gnulib/printf-args.c",
        "glib/gnulib/printf-frexp.c",
        "glib/gnulib/printf-frexpl.c",
        "glib/gnulib/printf-parse.c",
        # "glib/gnulib/vasnprintf.c",
        "glib/gnulib/xsize.c",
    ] + glob([
        "glib/gnulib/*.h",
        "glib/*.h",
        "glib/deprecated/*.h",
    ]),
    hdrs = [
        "glib.h",
        "glib/gnulib/g-gnulib.h",
        "glib/gnulib/printf-frexp.c",
        "os/windows/config.h",
        "os/windows/glib/glibconfig.h",
        "os/windows/glib/gnulib/gnulib_math.h",
    ],
    includes = [
        "os/windows",
        "os/windows/glib",
        "os/windows/glib/gnulib",
    ],
)

# Note we merge gmodule inside this.
cc_library(
    # Named "glib2" so it doesn't shadow the "glib" directory in this package.
    name = "glib-2.0",
    srcs = [
        "gmodule/gmodule.c",
        "glib/garcbox.c",
        "glib/garray.c",
        "glib/gasyncqueue.c",
        "glib/gatomic.c",
        "glib/gbacktrace.c",
        "glib/gbase64.c",
        "glib/gbitlock.c",
        "glib/gbookmarkfile.c",
        "glib/gbytes.c",
        "glib/gcharset.c",
        "glib/gchecksum.c",
        "glib/gconvert.c",
        "glib/gdataset.c",
        "glib/gdate.c",
        "glib/gdatetime.c",
        "glib/gdir.c",
        "glib/genviron.c",
        "glib/gerror.c",
        "glib/gfileutils.c",
        # "ggettext.c", # This requires the gettext packages.
        "glib/ghash.c",
        "glib/ghmac.c",
        "glib/ghook.c",
        "glib/ghostutils.c",
        "glib/giochannel.c",
        "glib/gkeyfile.c",
        "glib/glib-init.c",
        "glib/glib-private.c",
        "glib/glist.c",
        "glib/gmain.c",
        "glib/gmappedfile.c",
        "glib/gmarkup.c",
        "glib/gmem.c",
        "glib/gunicollate.c",
        "glib/gmessages.c",
        "glib/gnode.c",
        "glib/goption.c",
        "glib/gpathbuf.c",
        "glib/gpattern.c",
        "glib/gpoll.c",
        "glib/gprimes.c",
        "glib/gprintf.c",
        "glib/gqsort.c",
        "glib/gquark.c",
        "glib/gqueue.c",
        "glib/grand.c",
        "glib/grcbox.c",
        "glib/grefcount.c",
        "glib/grefstring.c",
        "glib/gregex.c",
        "glib/gscanner.c",
        "glib/gsequence.c",
        "glib/gshell.c",
        "glib/gslice.c",
        "glib/gslist.c",
        "glib/gstdio.c",
        "glib/gstrfuncs.c",
        "glib/gstring.c",
        "glib/gstringchunk.c",
        "glib/gstrvbuilder.c",
        "glib/gtestutils.c",
        "glib/gthread.c",
        "glib/gthreadpool.c",
        "glib/gtimer.c",
        "glib/gtimezone.c",
        "glib/gtrace.c",
        "glib/gtranslit.c",
        "glib/gtrashstack.c",
        "glib/gtree.c",
        "glib/gunibreak.c",
        "glib/gunidecomp.c",
        "glib/guniprop.c",
        "glib/guri.c",
        "glib/gutf8.c",
        "glib/gutils.c",
        # "guuid.c", # needs libintl.h from gettext
        "glib/gvariant-core.c",
        "glib/gvariant-parser.c",
        "glib/gvariant-serialiser.c",
        "glib/gvariant.c",
        "glib/gvarianttype.c",
        "glib/gvarianttypeinfo.c",
        "glib/gversion.c",
        "glib/gwakeup.c",
        "glib/libcharset/localcharset.c",
        "gmodule/gmodule.h",
    ] + select({
        "@platforms//os:macos": [
            "glib/giounix.c",
            "glib/glib-unix.c",
            "glib/glib-unixprivate.h",
            "glib/gspawn.c",
            "glib/gthread-posix.c",
            "os/darwin/config.h",
            "os/darwin/glib/glibconfig.h",
            "os/darwin/gmodule/gmoduleconf.h",
        ],
        "@platforms//os:windows": [
            "glib/dirent/dirent.h",
            "glib/dirent/wdirent.c",
            "glib/giowin32.c",
            "glib/gspawn-win32.c",
            "glib/gthread-win32.c",
            "glib/gwin32.c",
            "os/windows/config.h",
            "os/windows/glib/glibconfig.h",
            "os/windows/gmodule/gmoduleconf.h",
        ],
        "@platforms//os:linux": [
            "glib/giounix.c",
            "glib/gjournal-private.c",
            "glib/glib-unix.c",
            "glib/glib-unixprivate.h",
            "glib/gspawn.c",
            "glib/gthread-posix.c",
            "os/linux/config.h",
            "os/linux/glib/glibconfig.h",
            "os/linux/gmodule/gmoduleconf.h",
        ],
        "//conditions:default": [],
    }) + glob(
        [
            "glib/*.h",
            "glib/gnulib/*.h",
            "glib/deprecated/*.h",
            "glib/libcharset/*.h",
        ],
        exclude = [
            "glib/glib-unixprivate.h",
        ],
    ),
    hdrs = [
        "glib.h",
        "gmodule/gmodule-dl.c",  # TODO: this technically leaks out.
        "gmodule/gmodule-visibility.h",
    ] + select({
        "@platforms//os:windows": [
            "glib/dirent/dirent.c",
            "glib/gstdio-private.c",
            "glib/gwin32-private.c",
            "glib/win_iconv.c",
            "gmodule/gmodule-win32.c",
        ],
        "//conditions:default": [],
    }),
    copts = [
        "-Winvalid-pch",
        "-Wextra",
        "-Wpedantic",
        "-fno-strict-aliasing",
        "-Wimplicit-fallthrough",
        "-Wmisleading-indentation",
        "-Wmissing-field-initializers",
        "-Wnonnull",
        "-Wunused",
        "-Wno-unused-parameter",
        "-Wno-cast-function-type",
        "-Wno-pedantic",
        "-Wno-format-zero-length",
        "-Wno-variadic-macros",
        "-Werror=format=2",
        "-Werror=init-self",
        "-Werror=missing-include-dirs",
        "-Werror=pointer-arith",
        "-Werror=unused-result",
        "-Wstrict-prototypes",
        "-Wno-bad-function-cast",
        "-Werror=implicit-function-declaration",
        "-Werror=missing-prototypes",
        "-Wduplicate-decl-specifier",
        "-Werror=pointer-sign",
        "-Wno-string-plus-int",
    ] + select({
        # Needed for using <glib/xxx> vs "glib/xxxx"
        "@platforms//os:macos": [
            "-fvisibility=hidden",
            "-std=gnu99",
            "-I $(execpath os/darwin)",
            "-I $(execpath os/darwin/glib)",
            "-I $(execpath os/darwin/gmodule)",
            "-I $(execpath glib)",
            "-I $(execpath .)",
        ],
        "@platforms//os:windows": [
            "-Wno-inconsistent-dllimport",
            "-Wno-implicit-fallthrough",
            "-Wno-unused-function",
            "-Wno-#pragma-messages",
        ],
        "@platforms//os:linux": [
            "-fvisibility=hidden",
            "-std=gnu99",
        ],
        "//conditions:default": [],
    }),
    data = [
        # These paths are here so we can use them in copts with $(execpath ...)
        "os/darwin",
        "os/darwin/glib",
        "os/darwin/gmodule",
        "os/windows/gmodule",
        "glib",
        ".",
    ],
    includes = select({
        "@platforms//os:macos": [
            "os/darwin",
            "os/darwin/glib",
            "os/darwin/gmodule",
        ],
        "@platforms//os:linux": [
            "os/linux",
            "os/linux/glib",
            "os/linux/gmodule",
        ],
        "@platforms//os:windows": [
            "os/windows",
            "os/windows/glib",
            "os/windows/gmodule",
        ],
        "//conditions:default": [],
    }) + [
        ".",
        "glib",
        "gmodule",
    ],
    local_defines = [
        "GLIB_COMPILATION",
        "_GNU_SOURCE",
        "G_DISABLE_CAST_CHECKS",
        'GLIB_CHARSETALIAS_DIR=\\"\\"',
    ],
    deps = select({
        "@platforms//os:macos": [":glib-darwin"],
        "@platforms//os:windows": [":gnulib"],
        "//conditions:default": [],
    }) + ["@pcre2"],
)
